kmermake: lomex.cpp
	g++ -DBOOST_LOG_DYN_LINK -Wall -o lomex-main.out lomex.cpp fun_kmers.cpp fun_consensus.cpp file_reader.cpp file_writer.cpp search_step.cpp consensus_step.cpp hashing.cpp -lboost_program_options -lboost_log -lpthread -lboost_system -lboost_filesystem -fopenmp -O3 -std=c++11
